### ISSUE TITLE
APOC and APFR in seq03-33 genepop

### ISSUE THREAD

**Issue by katcatalano** [pinskylab/genomics#11]
There is a fish designated as APOC in their metadata (fish_spp) in the genepop (APCL18_291 | L3855 | gen_id=4129) and a fish designated as APFR (APCL17_207 | L4437 | gen_id=4338).
Are these just typos, or should I remove them from the parentage files?
Thanks!

**Comment by mstuart1** [comment]
These were type-os,  I have fixed them in the database.  Good catch!  - fix was done [here](
https://github.com/pinskylab/leyteBuildDB/commit/6a2cb6af0ca084b94cd0c4345e85253923f3bd69) 

I also added a note to check for samples that are non-APCL in the data sheet  for future field seasons so that we catch this sort of thing the day we enter data.

**Comment by katcatalano** [comment]
Nice! Thanks!!

**Comment by katcatalano** [comment]
I think we have one more typo, a sequenced fish listed as fish_spp= APOC
APCL13_429, L1637, gen_id=550

**Comment by mstuart1** [comment]
Malin captured 4 fish in 2013 that are non-APCL.  They have now been added to the known issues list.
